FROM node:latest

RUN apt-get update && apt-get install -y python3 python3-pip nodejs npm
RUN pip3 install --break-system-packages flask flask-cors gunicorn jwt

WORKDIR /app
COPY . /app/

WORKDIR /app/frontend/
RUN npm install
RUN npm run build

WORKDIR /app

EXPOSE 3000 5000

RUN chmod +x /app/run.sh

ENTRYPOINT ["/app/run.sh"]
