name: Build and Run Website

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t website .

      - name: Run Docker container
        run: |
          docker run -d -p 8080:3000 --name blog website

      - name: Archive build artifacts
        run: |
          mkdir -p /artifacts
          cp -r ./* /artifacts/
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: /artifacts/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
